# Generated by Django 4.1 on 2022-08-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='employees',
        ),
        migrations.AddField(
            model_name='manager',
            name='employees',
            field=models.ManyToManyField(blank=True, null=True, to='timetracking.employee'),
        ),
    ]
